[versions]
coroutines = "1.7.1"
kotlin = "1.8.21"
compose-ui = "1.4.3"
compose-compiler = "1.4.7"
activity-ktx = "1.7.1"
core-ktx = "1.10.1"
lifecycle-ktx = "2.6.1"
workmanager-ktx = "2.8.1"
window = "1.0.0"
paging-runtime = "3.2.0-alpha05"
activity-compose = "1.7.1"
navigation-compose = "2.5.3"
compose-material = "1.4.3"
compose-foundation = "1.4.3"
compose-runtime = "1.4.3"
compose-paging = "1.0.0-alpha19"
test-junit = "1.1.5"
test-espresso = "3.5.1"
snapper = "0.3.0"
junit = "4.13.2"

[libraries]

kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }

kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
kotlin-stdlib-common = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib-common", version.ref = "kotlin" }

androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activity-ktx" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
androidx-lifecycle-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle-ktx" }
androidx-workmanager-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workmanager-ktx" }
androidx-window = { module = "androidx.window:window", version.ref = "window" }
androidx-paging-runtime = { module = "androidx.paging:paging-runtime", version.ref = "paging-runtime" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation-compose" }
androidx-compose-material = { module = "androidx.compose.material:material", version.ref = "compose-material" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose-foundation" }
androidx-compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "compose-runtime" }
androidx-paging-compose = { module = "androidx.paging:paging-compose", version.ref = "compose-paging" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose-ui" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose-ui" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "compose-ui" }
androidx-compose-ui-test = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "compose-ui" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "compose-ui" }
androidx-test-junit = { module = "androidx.test.ext:junit", version.ref = "test-junit" }
androidx-test-espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "test-espresso" }

chrisbanes-snapper = { module = "dev.chrisbanes.snapper:snapper", version.ref = "snapper" }

junit = { module = "junit:junit", version.ref = "junit" }

[plugins]
versions = { id = "com.github.ben-manes.versions", version = "0.45.0" }






